### DISCUSSION TITLE
I2P SAM parameters (within Docker)

### DISCUSSION THREAD

**Discussion by deavmi** [markqvist/Reticulum#540] [Help & Questions]
I am putting together an integrated Docker compose service file to satisfy my needs. One of these things includes the fact that I will be running `rnsd` and `i2pd` in seperate containers. The reticulum daemon, when setting up a `type = I2PInterface` assumes localhost address and a fixed SAM port.

Would it be possible to get these two parameters as options:

```toml
[[I2p Interface]]
type = I2PInterface
sam_addr = i2pd.machine
sam_port = 2121
```
